name: Spoke Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_USE_MSI: true
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: Spoke Destroy
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (with backend)
        run: terraform -chdir="Intellect_Spoke_Terraform_Script" init

      - name: Terraform destroy
        run: terraform -chdir="Intellect_Spoke_Terraform_Script" destroy --auto-approve